export type MODAL_VIEWS =
  | "INIT_VIEW"
  | "CONFIRM_VIEW"
  | "LOG_RECORD_ALERT_VIEW"
  | "PIN_EDIT_VIEW"
  | "LOG_RECORD_DONE_VIEW"
  | "PROFILE_EDIT_VIEW"
  | "MATE_CREATE_MAP_VIEW"
  | "MATE_LOCATION_MAP_VIEW"
  | "POST_CREATE_DONE_VIEW"
  | "ANIMATION_ALERT_VIEW";
