name: "Chromatic Deployment"
run-name: ${{ github.actor }}의 스토리북 배포

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: yarn

      - uses: chromaui/action@v1

        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
